#!/usr/bin/env npx ts-node
/**
 * Create BSC EVM wallets for treasury and backend.
 * Run: pnpm run create-bsc-wallets
 * Copy the output into memelab-backend/.env and frontend .env.local
 */
import { Wallet } from 'ethers';
import * as fs from 'fs';
import * as path from 'path';

function main() {
  // Treasury/backend wallet (receives user deposits, used for settlement)
  const treasury = Wallet.createRandom();
  const treasuryAddress = treasury.address;
  const treasuryPrivateKey = treasury.privateKey;

  // Optional: Deployer wallet (for deploying BEP-20 token - can use same as treasury)
  const deployer = Wallet.createRandom();
  const deployerAddress = deployer.address;
  const deployerPrivateKey = deployer.privateKey;

  const backendEnvPath = path.resolve(__dirname, '../.env');
  const frontendEnvPath = path.resolve(__dirname, '../../.env.local');

  const backendLines = [
    '',
    '# BSC wallets (generated by create-bsc-wallets.ts)',
    `TREASURY_WALLET_ADDRESS=${treasuryAddress}`,
    `BACKEND_WALLET_PRIVATE_KEY=${treasuryPrivateKey}`,
    '# Deployer (optional - for deploying BEP-20 token)',
    `# DEPLOYER_ADDRESS=${deployerAddress}`,
    `# DEPLOYER_PRIVATE_KEY=${deployerPrivateKey}`,
  ];

  const frontendLines = [
    '',
    '# BSC (from create-bsc-wallets - RPC only, no secrets)',
    'NEXT_PUBLIC_BSC_RPC_URL=https://bsc-dataseed1.binance.org',
    'NEXT_PUBLIC_BSC_CHAIN_ID=56',
  ];

  console.log('\n=== BSC Wallets Generated ===\n');
  console.log('SECURITY: Keep private keys secret. Never commit them to git.\n');
  console.log('Treasury wallet (receives deposits, backend settlement):');
  console.log('  Address:', treasuryAddress);
  console.log('  Private key:', treasuryPrivateKey);
  console.log('');
  console.log('Deployer wallet (optional, for deploying BEP-20):');
  console.log('  Address:', deployerAddress);
  console.log('  Private key:', deployerPrivateKey);
  console.log('\n--- Add to memelab-backend/.env ---\n');
  console.log(backendLines.join('\n'));
  console.log('\n--- Add to .env.local (frontend) ---\n');
  console.log(frontendLines.join('\n'));

  // Optionally append to .env: pnpm run create-bsc-wallets -- --write
  const appendTo = process.argv.includes('--write');
  if (appendTo) {
    try {
      if (fs.existsSync(backendEnvPath)) {
        const current = fs.readFileSync(backendEnvPath, 'utf-8');
        if (!current.includes('TREASURY_WALLET_ADDRESS=')) {
          fs.appendFileSync(backendEnvPath, '\n' + backendLines.filter(Boolean).join('\n'));
          console.log('\nAppended wallet vars to memelab-backend/.env');
        }
      }
      if (fs.existsSync(frontendEnvPath)) {
        const current = fs.readFileSync(frontendEnvPath, 'utf-8');
        if (!current.includes('NEXT_PUBLIC_BSC_RPC_URL=')) {
          fs.appendFileSync(frontendEnvPath, '\n' + frontendLines.filter(Boolean).join('\n'));
          console.log('Appended BSC vars to .env.local');
        }
      }
    } catch (e) {
      console.error('Could not write to env files:', e);
    }
  } else {
    console.log('\nTo append these to your .env files, run: pnpm run create-bsc-wallets -- --write');
  }
  console.log('');
}

main();
